- op: add
  path: /spec/generators/0/list/elements
  value:
    - cluster: local
      url: https://kubernetes.default.svc
      values:
        name: amq-streams-operator
        path: components/operators/amq-streams-operator/operator/overlays/stable
    - cluster: local
      url: https://kubernetes.default.svc
      values:
        name: openshift-data-foundation-operator
        path: components/operators/openshift-data-foundation/aggregate/overlays/aws-node-labeler-4.12