apiVersion: redhatcop.redhat.io/v1alpha1
kind: GitHubSecretEngineRole
metadata:
    name: redhat-se-rto
    namespace: vault-admin
spec:
  authentication: 
    path: dev-cluster-admin
    role: vault-admin
    serviceAccount:
      name: default
  path: github
  organizationName: "redhat-se-rto"
  repositories: []
  permissions: 
    pull_requests: write
    metadata: read
    contents: write
    repository_hooks: write