apiVersion: apps.gitlab.com/v1beta1
kind: GitLab
metadata:
  name: gitlab
  namespace: gitlab-system
spec:
  chart:
    version: 8.5.1
    values:
      certmanager-issuer:
        email: admin@example.com
      configureCertmanager:
        install: true
      global:
        hosts:
          domain: example.com # update with the cluster domain here.
        ingress:
          configureCertmanager: true
      nginx-ingress:
        enabled: false
