apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: gitlab-operator-kubernetes
  namespace: gitlab-system
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  channel: stable
  installPlanApproval: Automatic
  name: gitlab-operator-kubernetes
  # source: community-operators
  source: certified-operators
  sourceNamespace: openshift-marketplace
  # startingCSV: gitlab-operator-kubernetes.v0.19.0
  startingCSV: gitlab-operator-kubernetes.v0.25.1