apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../bases/vault-config/

patches:
  - patch: |-
      - op: replace
        path: /spec/applicationID
        value: 401106 #replace by your Github Org Id here!!!
      - op: replace
        path: /spec/gitHubAPIBaseURL
        value: 'https://api.github.com/' #replace by your Github Enterprise API URL here (eg: https://[YOUR_HOST]/api/v3/)
    target:
      kind: GitHubSecretEngineConfig
  - patch: |-
      - op: replace
        path: /spec/organizationName
        value: "redhat-na-ssa" #replace by your Github Org name here!!!
      - op: replace
        path: /metadata/name
        value: "redhat-na-ssa" #replace by your Github Org here!!!
    target:
      kind: GitHubSecretEngineRole
  - patch: |-
      - op: replace
        path: /spec/url
        value: "https://quay.io" #replace by your Quay instance URL here!!!
    target:
      kind: QuaySecretEngineConfig
  - patch: |-
      - op: replace
        path: /spec/namespaceName
        value: "redhat_na_ssa" #replace by your Quay Organization/namespace here!!!
      - op: replace
        path: /metadata/name
        # this value must consist of lower case alphanumeric characters, '-' or '.', and must start and end with an alphanumeric character
        value: "redhat-na-ssa" #replace by your Quay Organization/namespace here!!!
    target:
      kind: QuaySecretEngineRole